### ISSUE TITLE
Pregunta : Por qué dejo de funcionar?

### ISSUE THREAD

**Issue by Cshion** [erickgnavar/serpost#1]
Hola, me interesaría saber porque ya no funciona esto, me parece un proyecto interesante.

**Comment by erickgnavar** [comment]
Hola @Cshion , disculpa por la tardía respuesta, Github no notifica de los issues abiertos 😕, lo que pasó es que en la página de Serpost agregaron un captcha y no me ha dado tiempo de implementar una solución para resolver el captcha :(

**Comment by erickgnavar** [comment]
Se ha actualizado la librería ahora usando otra url de Serpost, funciona nuevamente 😃
